### ISSUE TITLE
add support for password protected certificate files

### ISSUE THREAD

**Issue by kkoshelev-g** [httplib2/httplib2#142]
add_certificate() function does support password protected cert files. Having file with the private key as in plane text is a big security risk.

I have a patch which adds that functionality but I am unable to unit test changes. The existing unit tests are broken. Would anyone suggest how to fix existing unit tests?

**Comment by temoto** [comment]
Thank you.

Please describe what exactly is broken about tests. How you run them and
what output you get?

**Comment by kkoshelev-g** [comment]
Thank you for the quick reply.
Perhaps I don't run tests correctly. I simply run test file.
~/github/httplib2/python2$ python httplib2test.py

What is the proper way to run all the tests?

**Comment by temoto** [comment]
`script/test`

Sorry for confusion, I still haven't cleaned old test suite after making
new.

**Comment by kkoshelev-g** [comment]
I'm just curious if tests pass on your machine or wherever they are run on (on master branch). I could not figure out how to set up environment where all tests pass and no flaky tests. Any help would be appreciated.

I created another fresh cloud instance - Ubuntu 18.04 this time, got stable build from httplib2/httplib2 and run tests. I got same results. Please see log attached with 13 failures. Please let me know if you are aware that those tests are broken or there is something different with my environment which causes breaks. I can try to fix those tests if it is something that needs to be done.

[test_http.log](https://github.com/httplib2/httplib2/files/3611649/test_http.log)

As for the pull request, I will and another test similar to test_get_via_https_key_cert() which will exercise code with password.

**Comment by temoto** [comment]
@kkoshelev-g thank you, that is helpful.
- `ssl.SSLContext() __new__() takes at least 2 arguments (1 given)` which is caused by Python2.7 require ssl version argument. It's skipped on Travis+2.7, I should've check `sys.version_info` instead. Sorry.
- `ResponseNotReady` that I don't understand yet. Please show output (on that machine) of `curl -v 'http://invalid.hostname.foo.bar/'` and `curl -v 'http://[::1]:1/'`
- `test_connection_refused_returns_response` basically checks system dependent connection-refused error string, in your case error string is empty. Maybe there is malicious DNS server which resolves anything.

As you can see all of them are not related to what you are trying to verify. I understand the irritation of not whole test suit pass. For this time, please bear inconvenience of separately running the required test with `script/test -k your_test_name` and CI will check everything reliably.

**Comment by kkoshelev-g** [comment]
No worries. I just wanted to make sure that I didn't break anything.

As for test_connection_refused_raises_exception it raises 
python2: http_client.ResponseNotReady
python3: socket.error

See outputs of curl and ping below:
kkoshelev@ubuntu-1804-1:~$ curl -v 'http://invalid.hostname.foo.bar/'
* Could not resolve host: invalid.hostname.foo.bar
* Closing connection 0
curl: (6) Could not resolve host: invalid.hostname.foo.bar
kkoshelev@ubuntu-1804-1:~$ curl -v 'http://[::1]:1/'
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 1 failed: Connection refused
* Failed to connect to ::1 port 1: Connection refused
* Closing connection 0
curl: (7) Failed to connect to ::1 port 1: Connection refused
kkoshelev@ubuntu-1804-1:~$ ping ::1
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.039 ms
64 bytes from ::1: icmp_seq=2 ttl=64 time=0.053 ms
64 bytes from ::1: icmp_seq=3 ttl=64 time=0.051 ms
^C
--- ::1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2052ms
rtt min/avg/max/mdev = 0.039/0.047/0.053/0.010 ms

Let me see if I can fix those tests.

**Comment by kkoshelev-g** [comment]
I updated pull request with unit test. Please take a look
